version: "2"
services:
  rabbitmq:
    image: rabbitmq:3.7.5-management
    container_name: rabbitmq-container
    network_mode: "host"
    hostname: localhost
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST:
    ports:
      - 5672:5672
      - 15672:15672

  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  mongodb:
    image: mongo:latest
    container_name: mongo-container
    network_mode: host
    hostname: localhost
    ports:
      - 27017:27017

  eureka-server:
    build: eureka-server/
    container_name: eureka-server
    restart: always
    network_mode: host
    hostname: localhost
    ports:
      - 8763:8763

  api-gateway:
    build: api-gateway/
    container_name: api-gateway
    depends_on:
      - eureka-server
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 9004:9004

  user-service:
    container_name: user-service
    build: user-service/
    hostname: localhost
    network_mode: host
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    restart: always

  authentication-service:
    container_name: authentication-service
    build: authentication-service/
    hostname: localhost
    network_mode: host
    ports:
      - 8082:8082
    depends_on:
      - mysql
    restart: always

  product-service:
    container_name: product-service
    build: product-service/
    hostname: localhost
    network_mode: host
    ports:
      - 8084:8084
    depends_on:
      - mongodb
    restart: always

  slot-service:
    container_name: slot-service
    build: slot-service/
    hostname: localhost
    network_mode: host
    ports:
      - 8085:8085
    depends_on:
      - mongodb
    restart: always

  order-service:
    container_name: order-service
    build: order-service/
    hostname: localhost
    network_mode: host
    ports:
      - 8087:8087
    depends_on:
      - mongodb
    restart: always

  payment-service:
    container_name: payment-service
    build: payment-service/
    hostname: localhost
    network_mode: host
    ports:
      - 8086:8086
    depends_on:
      - mongodb
    restart: always

  email-service:
    container_name: email-service
    build: email-service/
    hostname: localhost
    network_mode: host
    ports:
      - 8083:8083
    restart: always

  product-webapp:
    container_name: product-webapp
    build: product-webapp/
    hostname: localhost
    network_mode: host
    ports:
      - 4200:4200
    restart: always